routes/web.php
      Route::post('qtySetting/set', 'SkuController@setQtySetting');
			Route::post('price/store', 'SkuController@storePrice');
			Route::get('price/{sku_id}/{shop_id}', 'SkuController@getSkuPrice');
			Route::get('image', ['as' => 'skuImage.index', 'uses' => 'SkuController@indexImage']);
			Route::post('image', 'SkuController@setImage');
			Route::delete('image/{id}', 'SkuController@removeImage');
			Route::post('status', 'SkuController@setStatus');
			Route::get('{id}/clone','SkuController@cloneSku');
		});
		Route::resource('sku','SkuController', ['except' => ['show']]);

		Route::resource('carrier', 'CarrierController', ['except' => ['show']]);
		Route::resource('order','OrderController');
		Route::post('order/getSON','OrderController@getSON');
		Route::post('order/getDetail','OrderController@getDetail');
		Route::post('order/syncOrders','OrderController@syncOrders');
		Route::get('order/{prefix}/printOrder','OrderController@printOrder');
		Route::get('order/{prefix}/printInvoice','OrderController@printInvoice');
		Route::get('order/{prefix}/printShippingLabel','OrderController@printShippingLabel');
		Route::get('order/{prefix}/printStockList','OrderController@printStockList');
		Route::get('order/{prefix}/printCarrierManifest','OrderController@printCarrierManifest');
		Route::post('order/multiPrintOrders','OrderController@multiPrintOrders');
		Route::post('order/multiPrintInvoices','OrderController@multiPrintInvoices');
		Route::post('order/multiPrintShippingLabels','OrderController@multiPrintShippingLabels');
		Route::post('order/multiPrintStockLists','OrderController@multiPrintStockLists');
		Route::post('order/multiPrintCarrierManifests','OrderController@multiPrintCarrierManifests');
		Route::resource('logisticInventory','LogisticInventoryController');
		Route::resource('stockInLogistic','StockInLogisticController');
        Route::get('shippingList/checkout','ShippingListController@checkout');
        Route::resource('shippingList','ShippingListController');
        Route::post('shippingList/saveCheckout','ShippingListController@saveCheckout');
        Route::post('shippingList/detail','ShippingListController@detailByBinId');
        Route::post('shippingList/checkBarcode','ShippingListController@checkBarcode');
        Route::get('shippingList/{ID}/getTrackerNumber','ShippingListController@getTrackerNumber');


        Route::get('shippingStatus/{id}/print','ShippingStatusController@printReceipt');
		Route::get('shippingStatus/{id}/pdf','ShippingStatusController@getPDF');
		Route::resource('shippingStatus','ShippingStatusController');
		Route::resource('stockIn','StockInController');
		Route::get('pickingList/assign_tray/{id}','PickingListController@assign_tray');
		Route::post('pickingList/setTray','PickingListController@setTray');
		Route::resource('pickingList','PickingListController');
		Route::post('pickingList/getDetail','PickingListController@getDetail');
		Route::post('pickingList/orderList','PickingListController@orderList');
		Route::post('pickingList/getDetailInStock','PickingListController@getDetailInStock');
		Route::resource('picking','PickingController');
		Route::resource('pickingTypes','PickingTypeController');
		Route::resource('shippingBin','ShippingBinController');
		Route::resource('paymentMethod', 'PaymentMethodController', ['except' => ['show']]);
		Route::resource('packingList','PackingListController');
        Route::post('packingList/orderList','PackingListController@orderList');
        Route::post('packingList/savePACK','PackingListController@savePACK');
        Route::post('packingList/orderListEdit','PackingListController@orderListEdit');
        Route::post('packingList/loadPacking','PackingListController@loadPacking');
        Route::get('packingList/{ID}/printInvoice','PackingListController@printInvoice');

//        Route::post('packingList/loadPacking',['as' => 'packing.loadPacking','uses'=> 'PackingListController@loadPackingList']);
		Route::resource('zones', 'ZonesController', ['except' => ['show']]);

		Route::resource('supplier', 'SupplierController', ['except' => ['show']]);
		Route::group(['prefix' => 'supplier'], function() {
			Route::post('getSuppliers', ['as' => 'supplier.getSuppliers', 'uses' => 'SupplierController@getSuppliers']);
			// Route::post('genPrefix', ['as' => 'supplier.genPrefix', 'uses' => 'SupplierController@genPrefix']);
		});

		Route::resource('productCategories', 'ProductCatController', ['except' => ['show']]);
		Route::get('productCategories/{category}','ProductController@getProductCategories');
		Route::group(['prefix' => 'productCategories'], function() {
			Route::get('export/{type}', 'ProductCatController@export')->where('type', 'xls|pdf|html');
			Route::post('storeCategory', ['as' => 'productCategories.storeCategory', 'uses' => 'ProductCatController@storeCategory']);
			Route::post('storeLazadaCategories', 'ProductCatController@storeLazadaCategories');
			Route::post('getCategories', ['as' => 'productCategories.getCategories', 'uses' => 'ProductCatController@getCategories']);
			Route::post('getCategory', ['as' => 'productCategories.getCategory', 'uses' => 'ProductCatController@getCategory']);
			Route::post('getChildren', ['as' => 'productCategories.getChildren', 'uses' => 'ProductCatController@getChildren']);
		});

		Route::group(['prefix' => 'products'], function() {
			Route::get('{id}/clone', 'ProductController@cloneProduct');
			Route::get('export/{type}', 'ProductController@export')->where('type', 'xls|pdf|html');
			Route::post('checkPrefix', ['as' => 'products.checkPrefix', 'uses' => 'ProductController@checkPrefix']);
			Route::post('genPrefix', ['as' => 'products.genPrefix', 'uses' => 'ProductController@genPrefix']);
			Route::post('getProductIds', ['as' => 'products.getProductIds', 'uses' => 'ProductController@getProductIdList']);
			Route::get('categories/{parent}','ProductController@getCategories');
			Route::get('codeList/{category}','ProductController@getCodeList');
			Route::get('attributes/{category}','ProductController@getAttributes');
			Route::get('attributes/lazada/{category}','ProductController@getLazadaAttributes');
			Route::get('brands','ProductController@getBrands');
			Route::get('brands/{id}','ProductController@getBrands');
			Route::get('prefix/{prefix}','ProductController@validatePrefix');
			Route::get('data/{product_id}','ProductController@getProductData');
			Route::get('dataCode/{code_id}','ProductController@getProductCodeData');
			Route::get('productAttributes/{product}','ProductController@getProductAttributes');
			Route::get('productAttributes/{product}/{attribute}','ProductController@getProductAttributes');
			Route::get('suppliers/{category}','ProductController@getSuppliers');
		});

		Route::group(['prefix' => 'skuProducts'], function() {
//			Route::get('products', 'SKUProductsController@getProducts');
//			Route::post('checkPrefix', ['as' => 'skuProducts.checkPrefix', 'uses' => 'SKUProductsController@checkPrefix']);
//			Route::post('getProductsBySku', ['as' => 'skuProducts.getProductsBySku', 'uses' => 'SKUProductsController@getProductsBySku']);
		});

	    Route::resource('shop', 'ShopController');
	    Route::post('shop/storeCategory', ['as'=>'shop.storeCategory','uses'=>'ShopController@storeCategory']);
	    Route::get('shop/export/{type}', 'ShopController@export');
		Route::group(['prefix' => 'shop'], function() {
			Route::post('getShopsByName', ['as' => 'shop.getShopsByName', 'uses' => 'ShopController@getShopsByName']);
//			Route::post('getProductsBySku', ['as' => 'skuProducts.getProductsBySku', 'uses' => 'SKUProductsController@getProductsBySku']);
			Route::get('testApi/{account}/{api_key}', 'ShopController@testApi');
		});

		Route::group(['prefix' => 'zones'], function() {
			Route::post('checkPrefix', ['as' => 'zones.checkPrefix', 'uses' => 'ZonesController@checkPrefix']);
			Route::post('genPrefix', ['as' => 'zones.genPrefix', 'uses' => 'ZonesController@genPrefix']);
			Route::post('getZones', ['as' => 'zones.getZones', 'uses' => 'ZonesController@getZones']);
			Route::post('storeZone', ['as' => 'zones.storeZone', 'uses' => 'ZonesController@storeZone']);
		});

		Route::resource('reports', 'ReportsController', ['except' => ['show', 'create', 'edit', 'store', 'update', 'destroy']]);
	});
	Route::group([], function () {

		Route::group(['prefix' => 'warehouseMapping'], function() {
			Route::post('genPrefix', ['as' => 'warehouseMapping.genPrefix', 'uses' => 'WarehouseMappingController@genPrefix']);
			Route::post('checkPrefix', ['as' => 'warehouseMapping.checkPrefix', 'uses' => 'WarehouseMappingController@checkPrefix']);
			Route::post('getRacks', ['as' => 'warehouseMapping.getRacks', 'uses' => 'WarehouseRacksController@getRacks']);
		});
		Route::post('warehouseMappingTrays/genPrefix', ['as' => 'warehouseMappingTrays.genPrefix', 'uses' => 'WarehouseTraysController@genPrefix']);
		Route::group(['prefix' => 'warehouseMappingRacksCells'], function() {
			Route::post('genLocations', ['as' => 'warehouse.mapping.racks.genLocations', 'uses' => 'WarehouseCellsController@genLocations']);
			Route::post('getBarcodes', ['as' => 'warehouse.mapping.racks.getBarcodes', 'uses' => 'WarehouseCellsController@getBarcodes']);
		});
		Route::post('supplier/genPrefix', ['as' => 'supplier.genPrefix', 'uses' => 'SupplierController@genPrefix']);
        Route::post('warehouse/genPrefix', ['as' => 'warehouse.genPrefix', 'uses' => 'WarehouseController@genPrefix']);
        Route::post('warehouse/getContact', ['as' => 'warehouse.getContact', 'uses' => 'WarehouseController@getContact']);
	});

	Route::resource('profiles','ProfileController', ['except' => ['index', 'create', 'store', 'destroy']]);
	Route::get('file/{path}/{file}', 'FileController@getFile');

	//Route::get('orderType', 'OrderTypeController');

	Route::resource('orderType','OrderTypeController');
	Route::post('orderType/add', 'OrderTypeController@add');
	Route::post('orderType/edit', 'OrderTypeController@edit');

app/PackingList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PackingList extends Model {
	use Traits\Uuids;
    protected $table	= "t_packings";

	protected $fillable	= [
		"id",
		"packing_id",
		"order_id",
		"packing_date",
		"bin_id",
		"status",
		"insert_by",
		"update_by"
	];

	protected $hidden	= ['created_at','updated_at'];

	public function order()
	{
		return $this->belongsTo(Order::class, 'order_id', 'id');
	}

	public function staff()
	{
		return $this->belongsTo(User::class, 'insert_by', 'id');
	}
	
}

resources/views/admin/packingList/_packing_form.blade.php
<table class="table table-bordered table-hover dt-responsive nowrap" id="PackingListTABLE" cellspacing>
    <thead>
    <tr>
        <th>SKU</th>
        <th>BATCH ID</th>
        <th>PRODUCT NAME</th>
    </tr>
    </thead>
    <tbody>
    @foreach($order->detail as $key => $detail)
        <tr id="{{$detail->sku->sku}}">
            <td>{{$detail->sku->sku}}</td>
            <td>{{$detail->detailStock->batch_id}}</td>
            <td>{{$detail->sku->product->attribute('name')}}</td>
        </tr>
    @endforeach
    </tbody>
</table>
<input type="hidden" id="order_id_pack" value="{{$order->id}}" />

resources/views/admin/packingList/_printInvoice.blade.php
<div class="row">
    <div class="col-xs-3">
        <?php $barcode = Barcode::getBarcodePNG($order->order_no, "C128", 3, 100); ?>
        <div align="center">
            {{--<img src="data:image/png;base64,{{ $barcode }}" alt="{{ $order->order_no }}" width="100%" />--}}
            {{--{{ $order->order_no }}--}}
        </div>
    </div>
    <div class="col-xs-7">
        <div align="right">
            <h2 style="margin-top: 0">{{ $company->profile_name }}</h2>
            <p>{{ $company->profile_billing_address }}</p>
        </div>
    </div>
    <div class="col-xs-2">
        <img src="{{ File::exists("img/cProfiles/1.jpg") ? Asset("img/cProfiles/1.jpg") : Asset("img/logo-here.png") }}" width="100%">
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-5">
    </div>
    <div class="col-md-7">
        <h3>TAX INVOICE</h3>
    </div>
    <div class="col-xs-12 table-responsive">
        <table class="table table-bordered">
            <tbody>
            <tr>
                <td width="10%"><b>Invoice Number</b></td>
                <td width="15%">{{ $order->order_no }}</td>
                <td rowspan="4"><div align="center" style="margin-top: 30px;">
                        <img src="data:image/png;base64,{{ $barcode }}" alt="{{ $order->order_no }}" width="70%" />
                        <br>{{ $order->order_no }}
                    </div></td>

            </tr>
            {{--<tr>--}}
                {{--<td><b>Order Number</b></td>--}}
                {{--<td>{{ $order->order_no }}</td>--}}

            {{--</tr>--}}
            <tr>
                <td><b>Order Date</b></td>
                <td>{{ $order->date }}</td>

            </tr>
            <tr>
                <td><b>Invoice To</b></td>
                <td>{{ $order->customer_name }}</td>

            </tr>
            <tr>
                <td><b>Invoice Date</b></td>
                <td>{{ $nowDate }}</td>

            </tr>
            </tbody>

        </table>
    </div>

</div>
{{--<hr/>--}}
<div class="row invoice-info">
    {{--<div class="col-sm-4 invoice-col">--}}
        {{--<address>--}}
            {{--<strong>{{ $order->shop->shop_name }}</strong><br>--}}
        {{--</address>--}}
    {{--</div>--}}
    {{--<div class="col-sm-4 invoice-col">--}}
        {{--<strong class="pull-right"></strong>--}}
    {{--</div>--}}
    <div class="col-sm-6 invoice-col">
        <h4><b>Billing Address</b></h4>
        <address>
            <strong>{{ $order->bill_first_name . " " . $order->bill_last_name }}</strong><br>
            {{ $order->bill_address }}<br>
            {{ $order->bill_address2 }}<br>
            Contact Number: {{ $order->main_phone_cust }}
        </address>
    </div>
    <div class="col-sm-6 invoice-col">
        <h4><b>Shipping Address</b></h4>
        <address>
            <strong>{{ $order->ship_first_name . " " . $order->ship_last_name }}</strong><br>
            {{ $order->ship_address_1 }}<br>
            {{ $order->ship_address_2 }}<br>
            Contact Number: {{ $order->ship_phone}}
        </address>
    </div>
</div>
{{--<h3><b>Payment method:</b> {{$order->payment_method}}</h3>--}}

<div class="row">
    <div class="col-xs-12 table-responsive">
        <h4>Your ordered items for <b>{{$order->shop_order_id}}</b></h4>
        {{--<h4>Your ordered items for <b>{{$order->shop->prefix}}</b></h4>--}}
    </div>
    <div class="col-xs-12 table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th><b>#</b></th>
                <th>Product Code</th>
                <th>Product Name</th>
                <th>Qty</th>
                <th>Price</th>
                <th>Amount</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($details as $key => $detail)
                <tr>
                    <td>{{++$key}}</td>
                    <td>{{$detail->sku->sku}}</td>
                    <td>{{$detail->sku->product->attributes()->where("name", "name")->first()->name}}</td>
                    <td>{{$detail->qty}}</td>
                    <td align="right">{{$currency->code . " " . number_format($detail->price, 2)}}</td>
                    <td align="right">{{$currency->code . " " . number_format($detail->qty * $detail->price, 2)}}</td>
                </tr>
            @endforeach
            </tbody>
            {{--<tfoot>--}}
            {{--<tr>--}}
                {{--<td colspan="5" align="right"><strong>Sub Total(inlc GST)</strong></td>--}}
                {{--<td align="right">{{ $currency->code . " " . number_format($order->subtotal, 2) }}</td>--}}
            {{--</tr>--}}
            {{--<tr>--}}
                {{--<td colspan="5" align="right"><strong>Shipping Cost</strong></td>--}}
                {{--<td align="right">{{ $currency->code . " " . number_format($order->shipping_cost, 2) }}</td>--}}
            {{--</tr>--}}
            {{--<tr>--}}
                {{--<td colspan="5" align="right"><strong>Tax</strong></td>--}}
                {{--<td align="right">{{ $currency->code . " " . number_format($order->tax, 2) }}</td>--}}
            {{--</tr>--}}
            {{--<tr>--}}
                {{--<td colspan="5" align="right"><strong>Total Amount</strong></td>--}}
                {{--<td align="right">{{ $currency->code . " " . number_format($order->total, 2) }}</td>--}}
            {{--</tr>--}}
            {{--</tfoot>--}}
        </table>
    </div>
</div>

<div class="row">
    <div class="col-xs-6">
        <p class="lead">Term and Condition</p>
        <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">{{ $order->remark }}</p>
    </div>
    <div class="col-xs-6">
        <div class="row">
            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <b>Subtotal (inc GST):</b>
            </div>
            <div class="col-xs-4"  align="right">
                <b>{{ $currency->code . " " . number_format($order->subtotal, 2) }}</b>
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <i>Less: Voucher Applied</i>
            </div>
            <div class="col-xs-4"  align="right">
                <i>-RM 0.00</i>
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-8">
                <hr style="margin-bottom: -1px; margin-top: 0px; border: 0.5px black solid;">
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <b>Total (inc GST):</b>
            </div>
            <div class="col-xs-4"  align="right">
                <b>{{ $currency->code . " " . number_format($order->subtotal, 2) }}</b>
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <i>Shipping (inc GST)</i>
            </div>
            <div class="col-xs-4"  align="right">
                <i>+{{ $currency->code . " " . number_format($order->shipping_cost, 2) }}</i>
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-8">
                <hr style="margin-bottom: -1px;    margin-top: 0px; border: 0.5px black solid;">
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <b>Net Paid:</b>
            </div>
            <div class="col-xs-4"  align="right">
                <b>{{ $currency->code . " " . number_format($order->subtotal+$order->shipping_cost, 2) }}</b>
            </div>


            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-8">
                <hr style="margin-bottom: -1px;    margin-top: 0px; border: 0.5px black solid;">
            </div>

            <div class="col-xs-12">
            <br>
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <i>Total (inc GST)</i>
            </div>
            <div class="col-xs-4"  align="right">
                <i>{{ $currency->code . " " . number_format($order->total, 2) }}</i>
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <i>*GST</i>
            </div>
            <div class="col-xs-4"  align="right">
                <i>-{{ $currency->code . " " . number_format($order->tax, 2) }}</i>
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-8">
                <hr style="margin-bottom: -1px;    margin-top: 0px; border: 0.5px black solid;">
            </div>

            <div class="col-xs-4" align="right"></div>
            <div class="col-xs-4" align="left">
                <b>Total (excl GST)</b>
            </div>
            <div class="col-xs-4"  align="right">
                <b>{{ $currency->code . " " . number_format($order->total, 2) }}</b>
            </div>


            {{--<div class="col-xs-4" align="right"></div>--}}
            {{--<div class="col-xs-8">--}}
                {{--<hr style="margin-bottom: -1px;    margin-top: 0px; border: 0.5px black solid;">--}}
            {{--</div>--}}

        </div>

    </div>
</div>

resources/views/admin/packingList/index.blade.php
@extends('layouts.lte.main')
@section('content')
    <div class="row">
        <div class="col-xs-12">
            @include('layouts.lte.status')
            <div class="box">
                <div class="box-header">
                    <div class="pull-right">
                        @can('create-packingList')
                            <a class="btn btn-primary btn-flat" href="{{URL::current().'/create'}}"><i class="fa fa-plus"></i> Create Packing</a>
                        @endcan
                    </div>
                    <div class="clear" style="clear: both;"></div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-hover dataTable dt-responsive nowrap" id="packingList-table" cellspacing>
                        <thead>
                        <tr>
                            <th>Packing ID</th>
                            <th style="width: 144px">Packing date</th>
                            <th style="width: 144px">Staff</th>
                            <th style="width: 144px">Status</th>
                            <th style="width: 140px;"></th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('styles')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ asset('assets/lte/plugins/datatables/dataTables.bootstrap.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/lte/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css') }}">
@endpush
@push('scripts')
<script src="{{ asset('assets/lte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/lte/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/lte/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js') }}"></script>
<script>
    $.ajaxSetup({
        headers: { "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content') }
    });

    var table = $('#packingList-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('packingList.index') !!}',
        columns: [
            { data: 'packing_id'},
            { data: 'packing_date'},
            { data: 'staff'},
            { data: 'packing_status', class : 'click'},
            { data: 'action', name: 'action', orderable: false, searchable: false }
        ],
    });
</script>
@endpush

resources/views/admin/packingList/printInvoice.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>{{ $order->order_no }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" href="{!! asset('assets/lte/bootstrap/css/bootstrap.css') !!}">
    {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> --}}
    <link rel="stylesheet" href="{!! asset('assets/lte/dist/css/AdminLTE.min.css') !!}">

    <style>
        body {
            /*padding-top: 30px;*/
        }
    </style>
</head>
<body onload="{{ $print ? 'window.print();' : ''}}">
<div class="wrapper">
    <section class="invoice">
        @include('admin.packingList._printInvoice')
    </section>
</div>
</body>
</html>